baseurl: https://docs.stack.jimmycai.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Stack Docs
DefaultContentLanguage: en

languages:
    en:
        title: Stack Docs
        weight: 1
        hasCJKLanguage: false
        languageName: English
    zh-cn:
        title: Stack 主题文档
        weight: 2
        hasCJKLanguage: true
        languageName: 中文

params:
    mainSections:
        - post
    rssFullContent: true
    favicon:

    footer:
        since: 2020

    sidebar:
        compact: true
        emoji:
        subtitle: Card-style Hugo theme designed for bloggers
        avatar:
            enabled: true
            local: true
            src: img/logo.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        page:
            - type: toc
            - type: search
            
related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        tabWidth: 4
